# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from muchain.proto import muchain_pb2 as muchain_dot_proto_dot_muchain__pb2


class MuChainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MineBlock = channel.unary_unary(
        '/MuChain/MineBlock',
        request_serializer=muchain_dot_proto_dot_muchain__pb2.Block.SerializeToString,
        response_deserializer=muchain_dot_proto_dot_muchain__pb2.Block.FromString,
        )
    self.ReceivePropagatedBlock = channel.unary_unary(
        '/MuChain/ReceivePropagatedBlock',
        request_serializer=muchain_dot_proto_dot_muchain__pb2.Block.SerializeToString,
        response_deserializer=muchain_dot_proto_dot_muchain__pb2.Response.FromString,
        )
    self.LatestBlock = channel.unary_unary(
        '/MuChain/LatestBlock',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=muchain_dot_proto_dot_muchain__pb2.Block.FromString,
        )
    self.Ping = channel.unary_unary(
        '/MuChain/Ping',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class MuChainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MineBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceivePropagatedBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LatestBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MuChainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MineBlock': grpc.unary_unary_rpc_method_handler(
          servicer.MineBlock,
          request_deserializer=muchain_dot_proto_dot_muchain__pb2.Block.FromString,
          response_serializer=muchain_dot_proto_dot_muchain__pb2.Block.SerializeToString,
      ),
      'ReceivePropagatedBlock': grpc.unary_unary_rpc_method_handler(
          servicer.ReceivePropagatedBlock,
          request_deserializer=muchain_dot_proto_dot_muchain__pb2.Block.FromString,
          response_serializer=muchain_dot_proto_dot_muchain__pb2.Response.SerializeToString,
      ),
      'LatestBlock': grpc.unary_unary_rpc_method_handler(
          servicer.LatestBlock,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=muchain_dot_proto_dot_muchain__pb2.Block.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MuChain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
